source 'https://rubygems.org'

gem "eyes_selenium"
gem "eyes_appium"
gem "rspec"
gem "parallel_tests"
gem "ffi"
gem 'rake'
gem 'eventmachine', '1.2.7', git: 'https://github.com/eventmachine/eventmachine.git', tag: 'v1.2.7'
gem 'selenium-webdriver', '3.142.7'