name: 'Python test'
description: 'Action to run Python packages tests'
inputs:
  eyes_version:
    description: 'Set the version which should be used for the eyes SDK'
    default: 'latest@'
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Start Selenium Server
      if: ${{matrix.use_selenium }}
      id: selenium
      uses: ./.github/actions/start_selenium
    - name: Framework python package install
      id: install
      uses: ./.github/actions/update_python_requirements
      with:
        package: ${{matrix.framework_package}}
        version: ${{matrix.version}}
        working-directory: ${{matrix.work_dir}}
    - name: Eyes SDK python package install
      id: eyes
      uses: ./.github/actions/update_python_requirements
      with:
        package: ${{matrix.eyes_package}}
        version: ${{inputs.eyes_version}}
        working-directory: ${{matrix.work_dir}}
    - name: Log extra info
      id: logging
      uses: ./.github/actions/chrome_version
    - name: Logging version generation
      uses: ./.github/actions/log_data_json
      with:
        package: ${{ steps.install.outputs.package_name }}
        version: ${{ steps.install.outputs.package_version }}
        os: ${{runner.os}}
        title: ${{ matrix.job_name }}
        selenium: ${{ steps.selenium.outputs.version }}
        matrix:  ${{ toJSON(matrix) }}
        work_dir: ${{matrix.work_dir}}
        chrome_version: ${{ steps.logging.outputs.chrome_version }}
        chromedriver_version: ${{ steps.logging.outputs.chromedriver_version }}
    - name: Install dependencies
      shell: bash
      working-directory: ${{matrix.work_dir}}
      run: pip install -r requirements.txt
    - name: List installed dependencies
      shell: bash
      working-directory: ${{matrix.work_dir}}
      run: pip list
    - name: Run tests
      shell: bash
      working-directory: ${{matrix.work_dir}}
      run: ${{matrix.test_command}}
