name: 'Install package'
description: 'Command to install package with the version'
inputs:
  package:
    description: "Package name"
    required: true
  working-directory:
    description: "Relative path to the directory where package should be installed"
    required: true
  legacy_npm_peers:
    description: "Flag indicating need to use legacy-npm-peers flags during install"
    required: false
  version:
    description: "Install version specified in input"
    required: false
runs:
  using: "node20"
  main: "dist/index.js"