name: 'Install package'
description: 'Command to install package with the version'
inputs:
  package:
    description: "Package name"
    required: true
  major:
    description: "Check major package version diff with latest"
    required: false
  minor:
    description: "Check minor package version diff with latest"
    required: false
  patch:
    description: "Check patch package version diff with latest"
    required: false
  working-directory:
    description: "Relative path to the directory where package should be installed"
    required: false
runs:
  using: "node16"
  main: "dist/index.js"