name: 'All languanges test runner'
description: 'Action to run all tests'
inputs:
  lang:
    description: "Choose lang to run"
    required: true
  eyes_version:
    description: 'Set the version which should be used for the eyes SDK'
    default: 'latest@'
    required: false

runs:
  using: "composite"
  steps:
    - name: Run JS test
      if: ${{inputs.lang == 'js'}}
      uses: ./.github/actions/test_js
      with:
        eyes_version: ${{inputs.eyes_version}}
    - name: Run Python test
      if: ${{inputs.lang == 'python'}}
      uses: ./.github/actions/test_py
      with:
        eyes_version: ${{inputs.eyes_version}}
    - name: Run Ruby test
      if: ${{inputs.lang == 'ruby'}}
      uses: ./.github/actions/test_ruby
      with:
        eyes_version: ${{inputs.eyes_version}}
    - name: Run Java test
      if: ${{inputs.lang == 'java'}}
      uses: ./.github/actions/test_java
      with:
        eyes_version: ${{inputs.eyes_version}}
    - name: Run Dotnet test
      if: ${{inputs.lang == 'dotnet'}}
      uses: ./.github/actions/test_dotnet
      with:
        eyes_version: ${{inputs.eyes_version}}
    - name: Check input
      if: ${{ !contains(fromJSON('["js","python", "ruby", "java", "dotnet"]'), inputs.lang) }}
      shell: bash
      run: |
        echo "Unsupported test lang was used ${{inputs.lang}}"
        exit 1
