name: 'Install package'
description: 'Command to install package with the version'
inputs:
  package:
    description: "Package name"
    required: false
  version:
    description: "Package version"
    required: false
  os:
    description: "Current job os"
    required: false
  matrix:
    description: "Current job matrix settings"
    required: false
  work_dir:
    description: "Current job working dir"
    required: false
  selenium:
    description: "Framework selenium usage"
    required: false
  chrome_version:
    description: "Chrome version"
    required: false
  chromedriver_version:
    description: "Chromedriver version"
    required: false
  Appium_client:
    description: "Appium client version"
    required: false
  title:
    description: "Custom title name"
    required: false

runs:
  using: "node16"
  main: "dist/index.js"