# check window with default fully with css stitching
# Generated by Ruby template
require 'appium_helper'

RSpec.describe 'Coverage Tests' do
  let(:ufg) { false }
  let(:caps) {
    caps = {
      "browserName": '',
      "platformName": 'iOS',
      "appium:platformVersion": '16.0',
      "appium:newCommandTimeout": 600,
      "appium:app": 'storage:filename=awesomeswift_classic.app.zip',
      "appium:deviceName": 'iPhone 8 Simulator',
      "appium:automationName": 'XCUITest',
      "appium:orientation": orientation,
      'sauce:options': sauce_options
    }
    caps
  }

  it 'Window' do
    eyes.configure do |conf|
      conf.app_name = 'Applitools Support Matrix'
      conf.test_name = 'Appium iOS window - Classic (Ruby)'
    end
    eyes.open(driver: driver)
    eyes.check(Applitools::Appium::Target.window)
    eyes.close(true)
  end

end

