# check window with default fully with vg
# Generated by Ruby template
require 'selenium_helper'

RSpec.describe 'Coverage Tests' do
  let(:ufg) { true }

  it 'CheckWindowWithDefaultFullyWithVg' do
    driver.get('https://applitools.github.io/demo/TestPages/FramesTestPage/')
    eyes.configure do |conf|
      conf.app_name = 'Applitools Support Matrix'
      conf.test_name = 'Window - UFG'
      conf.viewport_size = Applitools::RectangleSize.new(700, 460)
    end
    eyes.open(driver: driver)
    eyes.check(Applitools::Selenium::Target.window)
    eyes.close(true)
  end

  it 'CheckRegionByCoordinatesWithVg' do
    driver.get('https://applitools.github.io/demo/TestPages/FramesTestPage/')
    eyes.configure do |conf|
      conf.app_name = 'Applitools Support Matrix'
      conf.test_name = 'Region - UFG'
      conf.viewport_size = Applitools::RectangleSize.new(700, 460)
    end
    eyes.open(driver: driver)
    eyes.check(Applitools::Selenium::Target.region(Applitools::Region.new(50, 70, 90, 110)))
    eyes.close(true)
  end
end

