name: 'Close batch'
description: 'Command to start selenium server on different platforms'
inputs:
  server:
    description: "Eyes server which is used in the tests"
    required: true
    default: 'https://eyes.applitools.com/'
  api_key:
    description: "Eyes api key which is used in the tests"
    required: true
  batch_id:
    description: "Batch id which should be closed"
    required: true
runs:
  using: "composite"
  steps:
    - run: curl -v -X --show-error --fail DELETE "${{inputs.server}}api/sessions/batches/${{inputs.batch_id}}/close/bypointerid?apiKey=${{inputs.api_key}}"
      shell: bash