# check window with default fully with css stitching
# Generated by Ruby template
require 'appium_helper'

RSpec.describe 'Coverage Tests' do
  let(:ufg) { true }
  let(:caps) {
    api_key = ENV["APPLITOOLS_API_KEY"]
    args = "--es APPLITOOLS \"{\"NML_API_KEY\":\""+ api_key +"\", \"NML_SERVER_URL\":\"https://eyesapi.applitools.com\"}\""
    caps = {
      "browserName": '',
      "platformName": 'Android',
      "appium:platformVersion": '11.0',
      "appium:newCommandTimeout": 600,
      "appium:app": 'storage:filename=android_nmg.apk',
      "appium:deviceName": 'Google Pixel 5 GoogleAPI Emulator',
      "appium:automationName": 'UiAutomator2',
      "appium:autoGrantPermissions": true,
      "appium:optionalIntentArguments": args,
      'sauce:options': {
        "username": ENV["SAUCE_USERNAME"],
        "accessKey": ENV["SAUCE_ACCESS_KEY"],
        "name": 'Support Matrix'
      }

    }
    caps
  }
  let(:iphone_8) {Applitools::Selenium::IosDeviceInfo.new(device_name: IosDeviceName::IPhone_8, screen_orientation: Orientation::PORTRAIT)}

  it 'Window' do
    eyes.configure do |conf|
      conf.app_name = 'Applitools Support Matrix'
      conf.test_name = 'Appium Android window - UFG (Ruby)'
      conf.add_mobile_device(iphone_8)
    end
    eyes.open(driver: driver)
    eyes.check(Applitools::Appium::Target.window)
    eyes.close(true)
  end

end

