# check window with default fully with css stitching
# Generated by Ruby template
require 'appium_helper'

RSpec.describe 'Coverage Tests' do
  let(:ufg) { false }
  let(:caps) {
    caps = {
      "browserName": '',
      "platformName": 'Android',
      "appium:platformVersion": '11.0',
      "appium:newCommandTimeout": 600,
      "appium:app": 'storage:filename=android_nmg.apk',
      "appium:deviceName": 'Google Pixel 5 GoogleAPI Emulator',
      "appium:automationName": 'UiAutomator2',
      "appium:autoGrantPermissions": true,
      'sauce:options': {
        "username": ENV["SAUCE_USERNAME"],
        "accessKey": ENV["SAUCE_ACCESS_KEY"],
        "name": 'Support Matrix Ruby'
      }
    }
    caps
  }

  it 'Window' do
    eyes.configure do |conf|
      conf.app_name = 'Applitools Support Matrix'
      conf.test_name = 'Appium Android window - Classic (Ruby)'
    end
    eyes.open(driver: driver)
    eyes.check(Applitools::Appium::Target.window)
    eyes.close(true)
  end

end

