# check window with default fully with css stitching
# Generated by Ruby template
require 'selenium_helper'

RSpec.describe 'Coverage Tests' do
  let(:ufg) { false }

  it 'CheckWindowWithDefaultFullyWithCssStitching' do
    driver.get('https://applitools.github.io/demo/TestPages/FramesTestPage/')
    eyes.configure do |conf|
      conf.app_name = 'Eyes Selenium SDK - Classic API'
      conf.test_name = 'CheckWindowDefaultFully'
      conf.viewport_size = Applitools::RectangleSize.new(700, 460)
    end
    eyes.open(driver: driver)
    eyes.check(Applitools::Selenium::Target.window)
    eyes.close(true)
  end

  it 'CheckRegionByCoordinatesWithCssStitching' do
    driver.get('https://applitools.github.io/demo/TestPages/FramesTestPage/')
    eyes.configure do |conf|
      conf.app_name = 'Eyes Selenium SDK - Fluent API'
      conf.test_name = 'TestCheckRegionByCoordinates_Fluent'
      conf.viewport_size = Applitools::RectangleSize.new(700, 460)
    end
    eyes.open(driver: driver)
    eyes.check(Applitools::Selenium::Target.region(Applitools::Region.new(50, 70, 90, 110)))
    eyes.close(true)
  end

  it 'CheckFrameWithCssStitching' do
    eyes.branch_name = "universal-sdk"
    driver.get('https://applitools.github.io/demo/TestPages/FramesTestPage/')
    eyes.configure do |conf|
      conf.app_name = 'Eyes Selenium SDK - Fluent API'
      conf.test_name = 'TestCheckFrame_Fluent'
      conf.viewport_size = Applitools::RectangleSize.new(700, 460)
    end
    eyes.open(driver: driver)
    eyes.check(Applitools::Selenium::Target.frame('[name="frame1"]'))
    eyes.close(true)
  end
end

