// Generated by DotNet template
using NUnit.Framework;
using Applitools.Utils.Geometry;
using Applitools.Selenium;
namespace Applitools.Support.Matrix.Tests
{
[TestFixture]
[Parallelizable]
public class CSS : BaseTest
{
    public override StitchModes getStitchMode() 
    {
        return StitchModes.CSS;
    }

    [Test]
    public void window()
    {
        driver.Navigate().GoToUrl("https://applitools.github.io/demo/TestPages/FramesTestPage/");
        eyes.Open(driver, "Applitools Support Matrix", "Window - Classic", new RectangleSize(width:700, height:460));
        eyes.Check(Target.Window());
        eyes.Close(true);
    }

    [Test]
    public void region()
    {
        driver.Navigate().GoToUrl("https://applitools.github.io/demo/TestPages/FramesTestPage/");
        eyes.Open(driver, "Applitools Support Matrix", "Region - Classic", new RectangleSize(width:700, height:460));
        eyes.Check(Target.Region(new System.Drawing.Rectangle(50, 70, 90, 110)));
        eyes.Close(true);
    }

    [Test]
    public void frame()
    {
        driver.Navigate().GoToUrl("https://applitools.github.io/demo/TestPages/FramesTestPage/");
        eyes.Open(driver, "Applitools Support Matrix", "Frame - Classic", new RectangleSize(width:700, height:460));
        eyes.Check(Target.Frame("frame1"));
        eyes.Close(true);
    }
  }
}