// Generated by DotNet template
using NUnit.Framework;
using Applitools.Utils.Geometry;
using Applitools.Selenium;
namespace Applitools.Support.Matrix.Appium
{
[TestFixture]
[Parallelizable]
public class Android_UFG : AppiumTest
{
    public override bool isUFG() 
    {
        return true;
    }
    
    public override DeviceTypes GetDevice() 
    {
        return DeviceTypes.Android;
    }

    [Test]
    // [Ignore("Skipped test due to bad screenshot")]
    public void window()
    {
            var conf = eyes.GetConfiguration();
            conf.AddMobileDevice(new VisualGrid.AndroidDeviceInfo(VisualGrid.AndroidDeviceName.Pixel_5, eyesOrientation));
            eyes.SetConfiguration(conf);
            eyes.Open(driver, "Applitools Support Matrix", "Appium Android window - UFG (Dotnet)");
            eyes.Check(Target.Window().Fully(false));
            eyes.Close(true);
    }

  }
}