// Generated by DotNet template
using NUnit.Framework;
using Applitools.Utils.Geometry;
using Applitools.Selenium;
using System;
using System.Diagnostics;
using System.Collections;

namespace Applitools.Support.Matrix.Appium
{
[TestFixture]
[Parallelizable]
public class iOS_Classic : AppiumTest
{
    public override StitchModes getStitchMode() 
    {
        return StitchModes.CSS;
    }

    [Test]
    public void window()
    {
        eyes.Open(driver, "Applitools Support Matrix", "Appium iOS window - Classic (Dotnet)");
        eyes.Check(Target.Window());
        eyes.Close(true);
    }
  }
}