name: Support_Matrix_Execution

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_vars:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
      SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
    name: Update env variables for appium versions
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Update vars
        uses: ./.github/actions/update_github_vars
        with:
          token: ${{secrets.PAT}}
  update_apps:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    name: Update native apps
    defaults:
      run:
        shell: bash
    steps:
      - name: Prepare apps
        run: |
          echo "Start update script"        
          echo "Download clean apps from jFrog"
          echo "Download applitoolsify script"
          echo "Inject applitools lib"
          echo "Download app to jFrog"