name: Update Appium vars and apps

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      SAUCE_USERNAME:
        required: true
      SAUCE_ACCESS_KEY:
        required: true
  schedule:
    - cron: '0 19 * * *'

permissions:
  contents: write


env:
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}


jobs:
  update_vars:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
      SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
    name: Update env variables for appium versions
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Update vars
        uses: ./.github/actions/update_github_vars
        with:
          token: ${{secrets.PAT}}
  update_ios_classic_app:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    name: Update ios classic app
    env:
      APP_NAME: "awesomeswift_classic.app.zip"
    defaults:
      run:
        shell: bash
    steps:
      - name: Download clean app
        run: |
          echo "Start update script"
          curl -L -o awesomeswift_classic.app.zip "https://drive.google.com/uc?export=download&id=1nCPvWeUIqd4yf64NTmxMpGd02GnxP6ay"
      - name: Prepare apps
        run: |
          ls -lh
      - name: Remove previous versions of app on Sauce
        run: |
          FILE_IDS=$(curl -s -u $SAUCE_USERNAME:$SAUCE_ACCESS_KEY "https://api.us-west-1.saucelabs.com/v1/storage/files?name=$APP_NAME" | jq -r '.items[].id')

          for FILE_ID in $FILE_IDS; do
            echo "Deleting app with ID: $FILE_ID"
            curl -s -X DELETE -u $SAUCE_USERNAME:$SAUCE_ACCESS_KEY "https://api.us-west-1.saucelabs.com/v1/storage/files/$FILE_ID"
          done

          echo "All matching apps have been deleted."
      - name: Upload to Sauce
        run: |
          echo $APP_NAME
          curl -v -u "$SAUCE_USERNAME:$SAUCE_ACCESS_KEY" --location \
          --request POST 'https://api.us-west-1.saucelabs.com/v1/storage/upload' \
          --form "payload=@./$APP_NAME" \
          --form "name=$APP_NAME"

  update_android_classic_apps:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    name: Update android nmg app
    env:
      APP_NAME: "SimpleRandomStock_classic.apk"
    defaults:
      run:
        shell: bash
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Download clean app
        run: |
          echo "Start update script"
          pip install gdown
          gdown  "https://drive.google.com/uc?confirm=no_antivirus&id=16M_Fu4OfTHFMi3bQsaFyrbj-kYXoxwOl" -O SimpleRandomStock.apk
          # curl -L -o SimpleRandomStock.apk "https://drive.google.com/uc?export=download&confirm=no_antivirus&id=16M_Fu4OfTHFMi3bQsaFyrbj-kYXoxwOl"
      - name: Prepare apps
        run: |
          mv SimpleRandomStock.apk "$APP_NAME"
          ls -lh
      - name: Remove previous versions of app on Sauce
        run: |
          FILE_IDS=$(curl -s -u $SAUCE_USERNAME:$SAUCE_ACCESS_KEY "https://api.us-west-1.saucelabs.com/v1/storage/files?name=$APP_NAME" | jq -r '.items[].id')
          
          for FILE_ID in $FILE_IDS; do
            echo "Deleting app with ID: $FILE_ID"
            curl -s -X DELETE -u $SAUCE_USERNAME:$SAUCE_ACCESS_KEY "https://api.us-west-1.saucelabs.com/v1/storage/files/$FILE_ID"
          done
          
          echo "All matching apps have been deleted."
      - name: Upload to Sauce
        run: |
          echo $APP_NAME
          curl -v -u "$SAUCE_USERNAME:$SAUCE_ACCESS_KEY" --location \
          --request POST 'https://api.us-west-1.saucelabs.com/v1/storage/upload' \
          --form "payload=@./$APP_NAME" \
          --form "name=$APP_NAME"
