name: Appium

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      APPLITOOLS_API_KEY:
        required: true
      SAUCE_USERNAME:
        required: true
      SAUCE_ACCESS_KEY:
        required: true

permissions:
  contents: read


env:
  APPLITOOLS_DONT_CLOSE_BATCHES: true
  APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY }}
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}


jobs:
  batch_id:
    name: Batch_id
    runs-on: ubuntu-latest
    outputs:
      uuid: ${{ steps.uuid.outputs.uuid }}
    steps:
      - name: generate uuid
        id: uuid
        run: |
          echo "::set-output name=uuid::$(uuidgen)"
  js:
    needs: batch_id
    runs-on: ubuntu-latest
    env:
      APPLITOOLS_BATCH_ID: ${{needs.batch_id.outputs.uuid}}
      JS_TESTS_CONFIG_NAME: 'eyes-selenium'
      work_dir: 'sdks/js/eyes-selenium'
    name: Javascript appium
    defaults:
      run:
        working-directory: ${{env.work_dir}}
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Logging version generation
        uses: ./.github/actions/log_data_json
        with:
          os: 'ubuntu'
          title: 'Javascript Appium'
          selenium: 'sauce'
      - name: Run tests
        run: |
          npm install
          npm run appium
  java:
    needs: batch_id
    runs-on: ubuntu-latest
    env:
      APPLITOOLS_BATCH_ID: ${{needs.batch_id.outputs.uuid}}
    name: 'Java Appium'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      - name: Logging version generation
        uses: ./.github/actions/log_data_json
        with:
          os: 'ubuntu'
          title: 'Java Appium'
          selenium: 'sauce'
      - name: Install dependency
        working-directory: sdks/java
        run: |
          mvn versions:use-latest-releases -Dincludes=com.applitools:eyes-appium-java5
          mvn versions:use-latest-releases -Dincludes=com.applitools:eyes-selenium-java5
      - name: Run tests
        working-directory: sdks/java
        run:  mvn test -DsuiteFile=appium.xml
  python:
    needs: batch_id
    runs-on: ubuntu-latest
    env:
      APPLITOOLS_BATCH_ID: ${{needs.batch_id.outputs.uuid}}
    name: 'Python Appium'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Logging version generation
        uses: ./.github/actions/log_data_json
        with:
          os: ubuntu
          title: 'python appium [3.10]'
          selenium: 'sauce'
      - name: Run tests
        working-directory: sdks/python
        run: |
          pip install -r requirements.txt
          pytest -c appium.ini
  ruby:
    needs: batch_id
    runs-on: ubuntu-latest
    env:
      APPLITOOLS_BATCH_ID: ${{needs.batch_id.outputs.uuid}}
    name: 'Ruby Appium'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: true
      - name: Install gems
        working-directory: sdks/ruby
        run: |
          bundle install
      - name: Logging version generation
        uses: ./.github/actions/log_data_json
        with:
          os: 'Ubuntu'
          title: 'Ruby appium [2.6]'
          selenium: 'sauce'
      - name: Run tests
        working-directory: sdks/ruby
        run: |
          bundle exec rake github:appium
  dotnet:
    needs: batch_id
    runs-on: ubuntu-latest
    env:
      APPLITOOLS_BATCH_ID: ${{needs.batch_id.outputs.uuid}}
    name: Dotnet ${{ matrix.dotnet-version }} ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '3.1.x'
      - name: Logging version generation
        uses: ./.github/actions/log_data_json
        with:
          os: ubuntu
          title: 'dotnet appium'
          selenium: 'sauce'
      - name: Run tests
        working-directory: sdks/dotnet/selenium
        run: |
          dotnet add package Eyes.Appium
          dotnet test -- NUnit.NumberOfTestWorkers=1        
