name: Update Appium vars and apps

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
#  update_vars:
#    runs-on: ubuntu-latest
#    timeout-minutes: 15
#    env:
#      SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
#      SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
#    name: Update env variables for appium versions
#    defaults:
#      run:
#        shell: bash
#    steps:
#      - uses: actions/checkout@v3
#      - name: Update vars
#        uses: ./.github/actions/update_github_vars
#        with:
#          token: ${{secrets.PAT}}
  update_ios_apps:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    name: Update native apps
    defaults:
      run:
        shell: bash
    steps:
      - name: Prepare apps
        run: |
          echo "Start update script"     
          curl -O https://drive.google.com/file/d/1xu9hfo5rZ101hZoDzA9HMZ8dtW0R5-4K/view?usp=share_link
          ls
          echo "Download applitoolsify script"
          echo "Inject applitools lib"
          echo "Download app to saucelabs (("
  update_android_apps:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    name: Update native apps
    defaults:
      run:
        shell: bash
    steps:
      - name: Prepare apps
        run: |
          echo "Start update script"     
          curl -O https://drive.google.com/file/d/16M_Fu4OfTHFMi3bQsaFyrbj-kYXoxwOl/view?usp=share_link
          ls
          echo "Download applitoolsify script"
          echo "Inject applitools lib"
          echo "Download app to saucelabs (("