name: Check distros flow

on:
  workflow_dispatch:
  push:

permissions:
  contents: read
  
jobs:

  selenium:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    name: Run Distros
    container: artem0tranduil/alpine_runner:latest
    env:
      work_dir: sdks/js/eyes-puppeteer
      APPLITOOLS_DONT_CLOSE_BATCHES: true
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
      JS_TESTS_CONFIG_NAME: eyes-puppeteer
    steps:
      - uses: actions/checkout@v3
      - name: Framework install
        id: install
        uses: ./.github/actions/install_npm_package
        with:
          package: puppeteer
          version: "latest@"
          working-directory: ${{env.work_dir}}
          legacy_npm_peers: false
      - name: Eyes SDK js package install
        id: eyes
        uses: ./.github/actions/install_npm_package
        with:
          package: "@applitools/eyes-puppeteer"
          version: "latest@"
          working-directory: ${{env.work_dir}}
          legacy_npm_peers: false
      - name: Pre run install
        shell: bash
        working-directory: ${{env.work_dir}}
        run: npm install
      - name: Print installed packages
        shell: bash
        working-directory: ${{env.work_dir}}
        run: npm ls
      - name: Temp fix before dockerfile update
        run: | 
          apk update
          apk upgrade
          apk add --update ca-certificates
          apk add chromium udev ttf-freefont nss freetype harfbuzz
          chromium --version
      - name: Run tests
        shell: bash
        working-directory: ${{env.work_dir}}
        env:
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
        run: npm test