name: Check Support_Matrix_Execution

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  java:
    uses: ./.github/workflows/java.yml
    secrets:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
  python:
    uses: ./.github/workflows/python.yml
    secrets:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
  failing_check:
    runs-on: ubuntu-latest
    steps:
      - run: |
         sleep 60 
         exit 1
  report_generation:
    if: always()
    needs: [ java,python,failing_check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Report generation
        uses: ./.github/actions/report
        with:
          token: ${{secrets.PAT}}
          run_id: ${{github.run_id}}
      - name: Check files
        run: |
          pwd
          sleep 20
          ls
      - name: Upload report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: report.html
  email_notification:
    needs: report_generation
    runs-on: ubuntu-latest
    env: 
      TEST_VAR: ${{failure()}}
    steps:
      - run: echo Reporting a failure
      - run: echo $TEST_VAR
      - name: Download report as artifact
        uses: actions/download-artifact@v3
        with:
          name: report
      - name: Send mail
        if: github.run_attempt > 1 && failure()
        uses: dawidd6/action-send-mail@v3
        with:
            server_address: smtp.gmail.com
            server_port: 465
            username: ${{ secrets.EMAIL_USERNAME }}
            password: ${{ secrets.EMAIL_PASSWORD }}
            subject: SUPPORT MATRIX run has failed job
            body: Test run check  !!!!!! Workflow ${{ github.workflow }} of ${{ github.repository }}. See attachments for the report to the results
            html_body: Test run check !!!!!!! Workflow ${{ github.workflow }} of ${{ github.repository }} <br>
                       See attachments for the report to the results
            attachments: report.html
            to: tranduil15@gmail.com
            from: Artem
  rerun:
    if: failure()
    runs-on: ubuntu-latest
    needs: [report_generation, email_notification]
    steps:
      - name: rerun
        if: github.run_attempt == 1
        run: curl -X POST -H "Accept:application/vnd.github+json" -H "Content-Type:application/json" -s -u "admin:${{ secrets.PAT }}" https://api.github.com/repos/${{ github.repository }}/actions/workflows/rerun_failed.yml/dispatches -d '{"ref":"${{github.ref}}", "inputs":{"run_id":"${{github.run_id}}"}}'
