name: Check selenium server

on:
  workflow_dispatch:

permissions:
  contents: read
  
jobs:
  selenium:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: check | os = ${{matrix.os}}
    steps:
      - name: Run Mac checks
        if: matrix.os == 'macos-latest'
        run: |
          selenium-server -Dwebdriver.chrome.driver=${{ env.CHROMEWEBDRIVER }}
      - name: Run not on Mac checks
        if: runner.os != 'macos-latest'
        run: |
          java -jar ${SELENIUM_JAR_PATH} -Dwebdriver.chrome.driver=${CHROMEWEBDRIVER}