name: Check selenium server

on:
  workflow_dispatch:

permissions:
  contents: read
  
jobs:

  selenium:
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: check | os = ${{matrix.os}}
    steps:
      - name: Run Mac checks
        if: matrix.os == 'macos-latest'
        run: |
          selenium-server standalone &
          sleep 10
          echo 'Let end'
      - name: Run not on Mac checks
        if: matrix.os != 'macos-latest'
        run: |
          java -jar ${SELENIUM_JAR_PATH} standalone &
          sleep 10
          echo 'Let end'