name: Check selenium server

on:
  workflow_dispatch:

permissions:
  contents: read
  
jobs:

  selenium:
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        legacy: ['true', 'false']
    runs-on: ${{ matrix.os }}
    name: ${{matrix.os}} | ${{matrix.legacy}}
    steps:
      - uses: actions/checkout@v3
      - name: Run Selenium
        uses: ./.github/actions/start_selenium
        with:
          legacy: ${{matrix.legacy}}
      - name: Check Selenium
        run: |
          ls
          sleep 30
          wget http://localhost:4444