name: Check install actions

on:
  workflow_dispatch:

permissions:
  contents: read
  
jobs:

  selenium:
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: ${{matrix.os}} | ${{matrix.legacy}}
    steps:
      - uses: actions/checkout@v3
      - name: Install default
        working-directory: 'sdks/js/eyes-selenium'
        run: |
          npm install
          npm ls
      - name: Latest
        uses: ./.github/actions/install_npm_package
        with:
          package: cypress
      - name: Check latest
        working-directory: 'sdks/js/eyes-selenium'
        run: |
          pwd
          npm ls
      - name: Major -1
        uses: ./.github/actions/install_npm_package
        with:
          package: cypress
          major: -1
          working-directory: "sdks/js/eyes-selenium"
      - name: Check major -1
        working-directory: 'sdks/js/eyes-selenium'
        run: |
          pwd
          npm ls
      - name: Minor -1
        uses: ./.github/actions/install_npm_package
        with:
          package: webdriverio
          minor: -1
          working-directory: "sdks/js/eyes-selenium"
      - name: Check minor -1
        working-directory: 'sdks/js/eyes-selenium'
        run: |
          pwd
          npm ls    
      - name: Patch -1
        uses: ./.github/actions/install_npm_package
        with:
          package: webdriverio
          patch: -1
          working-directory: "sdks/js/eyes-selenium"
      - name: Check patch -1
        working-directory: 'sdks/js/eyes-selenium'
        run: |
          pwd
          npm ls
      - name: Exact
        uses: ./.github/actions/install_npm_package
        with:
          package: webdriverio
          exact: "5.23.0"
          working-directory: "sdks/js/eyes-selenium"
      - name: Check Exact
        working-directory: 'sdks/js/eyes-selenium'
        run: |
          pwd
          npm ls