name: Check distros flow

on:
  workflow_dispatch:
  push:

permissions:
  contents: read
  
jobs:

  selenium:
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: ${{matrix.os}} | ${{matrix.legacy}}
    steps:
      - uses: actions/checkout@v3
      - name: Run Selenium
        uses: ./.github/actions/start_selenium
        with:
          legacy: ${{matrix.legacy}}
      - name: Check Selenium
        run: |
          ls