name: Check distros flow

on:
  workflow_dispatch:
  push:

permissions:
  contents: read
  
jobs:

  selenium:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    name: Run Distros
    container: artem0tranduil/alpine_runner:latest
    steps:
      - uses: actions/checkout@v3
      - name: Check checkout
        run: |
          ls
          pwd