name: Support_Matrix_Execution

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  java:
    uses: ./.github/workflows/java.yml
    secrets:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
  ruby:
    uses: ./.github/workflows/ruby.yml
    secrets:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
  python:
    uses: ./.github/workflows/python.yml
    secrets:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
  dotnet:
    uses: ./.github/workflows/dotnet.yml
    secrets:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
  js_playwright:
    uses: ./.github/workflows/js_playwright.yml
    secrets:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
  js_cypress:
    uses: ./.github/workflows/js_cypress.yml
    secrets:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
  js_cypress_v9-:
    uses: ./.github/workflows/js_cypress_v9.yml
    secrets:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
  js_testcafe:
    uses: ./.github/workflows/js_testcafe.yml
    secrets:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
  js_storybook:
    uses: ./.github/workflows/js_storybook.yml
    secrets:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
  js_selenium:
    uses: ./.github/workflows/js_selenium.yml
    secrets:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
  js_nightwatch:
    uses: ./.github/workflows/js_nightwatch.yml
    secrets:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
  js_protractor:
    uses: ./.github/workflows/js_protractor.yml
    secrets:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
  js_puppeteer:
    uses: ./.github/workflows/js_puppeteer.yml
    secrets:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
  js_webdriverio:
    uses: ./.github/workflows/js_webdriverio.yml
    secrets:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
  js_webdriverio4:
    uses: ./.github/workflows/js_webdriverio4.yml
    secrets:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
  js_webdriverio5:
    uses: ./.github/workflows/js_webdriverio5.yml
    secrets:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
  report_generation:
    if: always()
    needs: [ java,
             ruby,
             python,
             dotnet,
             js_selenium,
             js_playwright,
             js_webdriverio,
             js_webdriverio4,
             js_webdriverio5,
             js_nightwatch,
             js_protractor,
             js_puppeteer,
             js_cypress,
             js_cypress_v9-,
             js_testcafe,
             js_storybook ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Report generation
        uses: ./.github/actions/report
        with:
          token: ${{secrets.PAT}}
          run_id: ${{github.run_id}}
      - name: Check files
        run: |
          pwd
          ls
      - name: Upload report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: report.html
  email_notification:
    if: ${{failure()}}
    needs: [ java,
             ruby,
             python,
             dotnet,
             js_selenium,
             js_playwright,
             js_webdriverio,
             js_webdriverio4,
             js_webdriverio5,
             js_nightwatch,
             js_protractor,
             js_puppeteer,
             js_cypress,
             js_cypress_v9-,
             js_testcafe,
             js_storybook,
    ]
    runs-on: ubuntu-latest
    steps:
      - run: echo Reporting a failure
      - name: Send mail
        if: github.run_attempt > 1
        uses: dawidd6/action-send-mail@v3
        with:
            server_address: smtp.gmail.com
            server_port: 465
            username: ${{ secrets.EMAIL_USERNAME }}
            password: ${{ secrets.EMAIL_PASSWORD }}
            subject: SUPPORT MATRIX run has failed job
            body: Worflow ${{ github.workflow }} of ${{ github.repository }}
              java has status ${{needs.java.result}}
              python has status ${{needs.python.result}}
              ruby has status ${{needs.ruby.result}}
              dotnet has status ${{needs.dotnet.result}}
              js_playwright has status ${{needs.js_playwright.result}}
              js_cypress has status ${{needs.js_cypress.result}}
              js_cypress v < 10 has status ${{needs.js_cypress_v9-.result}}
              js_testcafe has status ${{needs.js_testcafe.result}}
              js_storybook has status ${{needs.js_storybook.result}}
              js_selenium has status ${{needs.js_selenium.result}}
              js_nightwatch has status ${{needs.js_nightwatch.result}}
              js_protractor has status ${{needs.js_protractor.result}}
              js_webdriverio has status ${{needs.js_webdriverio.result}}
              js_webdriverio4 has status ${{needs.js_webdriverio4.result}}
              js_webdriverio5 has status ${{needs.js_webdriverio5.result}}
            html_body: Worflow ${{ github.workflow }} of ${{ github.repository }} <br>
              java has status ${{needs.java.result}} <br>
              python has status ${{needs.python.result}} <br>
              ruby has status ${{needs.ruby.result}} <br>
              dotnet has status ${{needs.dotnet.result}} <br>
              js_playwright has status ${{needs.js_playwright.result}} <br>
              js_cypress has status ${{needs.js_cypress.result}} <br>
              js_cypress v < 10 has status ${{needs.js_cypress_v9-.result}} <br>
              js_testcafe has status ${{needs.js_testcafe.result}} <br>
              js_storybook has status ${{needs.js_storybook.result}} <br>
              js_selenium has status ${{needs.js_selenium.result}} <br>
              js_nightwatch has status ${{needs.js_nightwatch.result}} <br>
              js_protractor has status ${{needs.js_protractor.result}} <br>
              js_webdriverio has status ${{needs.js_webdriverio.result}} <br>
              js_webdriverio4 has status ${{needs.js_webdriverio4.result}} <br>
              js_webdriverio5 has status ${{needs.js_webdriverio5.result}} <br>
            to: yarden.ingber@applitools.com
            from: Artem
  rerun:
    if: failure()
    runs-on: ubuntu-latest
    needs: [report_generation, email_notification]
    steps:
      - name: rerun
        if: github.run_attempt == 1
        run: curl -X POST -H "Accept:application/vnd.github+json" -H "Content-Type:application/json" -s -u "admin:${{ secrets.PAT }}" https://api.github.com/repos/${{ github.repository }}/actions/workflows/rerun_run.yml/dispatches -d '{"ref":"${{github.ref}}", "inputs":{"run_id":"${{github.run_id}}"}}'