name: Support_Matrix_Execution

on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *'

permissions:
  contents: write

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      uuid: ${{ steps.uuid.outputs.uuid }}
      web: ${{ steps.matrix.outputs.web}}
      appium: ${{ steps.matrix.outputs.appium}}
    steps:
      - name: generate uuid
        id: uuid
        run: |
          echo "uuid=$(uuidgen)" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v3
      - name: generate matrix
        id: matrix
        uses: ./.github/actions/setup
        with:
          work_dir: 'sdks/js/eyes-webdriverio, sdks/js/eyes-testcafe, sdks/js/eyes-storybook, sdks/js/eyes-puppeteer, sdks/js/eyes-protractor, sdks/js/eyes-playwright, sdks/js/eyes-nightwatch, sdks/js/eyes-cypress, sdks/js/eyes-selenium, sdks/python, sdks/java, sdks/dotnet, sdks/ruby'
          last_passed: false
  web:
    needs: setup
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup.outputs.web) }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    env:
      APPLITOOLS_DONT_CLOSE_BATCHES: true
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
      APPLITOOLS_BATCH_ID: ${{needs.setup.outputs.uuid}}
      APPLITOOLS_BRANCH_NAME: ${{matrix.branch}}
      JS_TESTS_CONFIG_NAME: ${{matrix.js_config}}
    name: ${{ matrix.job_name }}
    defaults:
      run:
        working-directory: ${{matrix.work_dir}}
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Test
        uses: ./.github/actions/test_runner
        with:
          lang: ${{matrix.test_runner}}
  appium:
    needs: setup
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix: ${{ fromJson(needs.setup.outputs.appium) }}
    runs-on: ${{ matrix.os }}
    environment: ${{matrix.gh_environment}}
    timeout-minutes: 20
    env:
      APPLITOOLS_DONT_CLOSE_BATCHES: true
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
      APPLITOOLS_BATCH_ID: ${{needs.setup.outputs.uuid}}
      JS_TESTS_CONFIG_NAME: ${{matrix.js_config}}
      SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
      SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
      APPIUM_VERSION: ${{vars.APPIUM_VERSION}}
    name: ${{ matrix.job_name }}
    defaults:
      run:
        working-directory: ${{matrix.work_dir}}
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Test
        uses: ./.github/actions/test_runner
        with:
          lang: ${{matrix.test_runner}}
  report_generation:
    if: always()
    needs: [ web,
             appium
    ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Report generation
        uses: ./.github/actions/report
        with:
          token: ${{secrets.PAT}}
          run_id: ${{github.run_id}}
      - name: Upload report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: report.html
      - name: Prepare for commit
        run: |
          git config --global user.name 'AutoSupport'
          git config --global user.email 'autosupport@noreply.github.com'
          git fetch
          git reset --hard
          git pull
          git status
      - name: Last passed data update
        uses: ./.github/actions/make_last_passed_data
        with:
          token: ${{secrets.PAT}}
          run_id: ${{github.event.inputs.run_id}}
      - name: Commit files
        run: |
          pwd
          sleep 20
          ls
          cat last_passed.json
          git add last_passed.json
          git commit -m "Update last_passed.json file with the latest data"
          git push
  gh_pages_updates:
    if: ${{ success() || (failure() && github.run_attempt == 3 )}}
    needs: report_generation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'gh-pages'
      - name: Prepare for commit
        run: |
          git config --global user.name 'AutoSupport'
          git config --global user.email 'autosupport@noreply.github.com'
          git fetch
          git reset --hard
          git pull
          git status
      - name: Download report as artifact
        uses: actions/download-artifact@v3
        with:
          name: report
      - name: Check files
        run: |
          pwd
          ls
          mv report.html index.html
          git add index.html
          git commit -m "Update support matrix report file"
          git push

  email_notification_fail:
    if: failure()
    needs: report_generation
    runs-on: ubuntu-latest
    steps:
      - run: echo Reporting a failure
      - name: Download report as artifact
        uses: actions/download-artifact@v3
        with:
          name: report
      - name: Send mail
        if: github.run_attempt > 2
        uses: dawidd6/action-send-mail@v3
        with:
            server_address: smtp.gmail.com
            server_port: 465
            username: ${{ secrets.EMAIL_USERNAME }}
            password: ${{ secrets.EMAIL_PASSWORD }}
            subject: SUPPORT MATRIX FAILURE
            body: Failed Support Matrix Run Workflow ${{ github.workflow }} of ${{ github.repository }}. Link to the test report is => https://applitools.github.io/applitools_support_matrix/ See attachments for the report to the results
            html_body: Failed Support Matrix Run Workflow ${{ github.workflow }} of ${{ github.repository }} <br>
                       Link to the test report is => https://applitools.github.io/applitools_support_matrix/ <br>
                       See attachments for the report to the results
            attachments: report.html
            to: yarden.ingber@applitools.com, artem.borodavka@applitools.com, adam.carmi@applitools.com, ben.babayoff@applitools.com
            from: Artem
  email_notification_success:
    needs: report_generation
    runs-on: ubuntu-latest
    steps:
      - run: echo Reporting a failure
      - name: Download report as artifact
        uses: actions/download-artifact@v3
        with:
          name: report
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: SUPPORT MATRIX SUCCESS
          body: Success Support Matrix Run Workflow ${{ github.workflow }} of ${{ github.repository }}. Link to the test report is => https://applitools.github.io/applitools_support_matrix/ See attachments for the report to the results
          html_body: Success Support Matrix Run Workflow ${{ github.workflow }} of ${{ github.repository }} <br>
            Link to the test report is => https://applitools.github.io/applitools_support_matrix/ <br>
            See attachments for the report to the results
          attachments: report.html
          to: yarden.ingber@applitools.com, artem.borodavka@applitools.com, adam.carmi@applitools.com, ben.babayoff@applitools.com
          from: Artem
  rerun:
    if: failure()
    runs-on: ubuntu-latest
    needs: [report_generation, email_notification_fail]
    steps:
      - name: rerun
        if: github.run_attempt < 3
        run: curl -X POST -H "Accept:application/vnd.github+json" -H "Content-Type:application/json" -s -u "admin:${{ secrets.PAT }}" https://api.github.com/repos/${{ github.repository }}/actions/workflows/rerun_failed.yml/dispatches -d '{"ref":"${{github.ref}}", "inputs":{"run_id":"${{github.run_id}}"}}'
