name: Dotnet

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      APPLITOOLS_API_KEY:
        required: true

permissions:
  contents: read

jobs:
  batch_id:
    uses: ./.github/workflows/batch_id.yml
  test:
    needs: batch_id
    strategy:
      matrix:
        dotnet-version: [ '3.1.x' ]
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      APPLITOOLS_DONT_CLOSE_BATCHES: true
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
      APPLITOOLS_BATCH_ID: ${{needs.batch_id.outputs.uuid}}
    name: Dotnet ${{ matrix.dotnet-version }} ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Start Selenium Server
        uses: ./.github/actions/start_selenium
      - name: Run tests
        working-directory: sdks/dotnet
        run: |
          dotnet add package Eyes.Selenium
          dotnet test -- NUnit.NumberOfTestWorkers=1