name: Dotnet

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      APPLITOOLS_API_KEY:
        required: true

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        dotnet-version: [ '3.1.x' ]
    runs-on: windows-latest
    env:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
    name: Dotnet ${{ dotnet-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Run tests
        working-directory: sdks/dotnet
        run: |
          dotnet test -- NUnit.NumberOfTestWorkers=2