name: JS Cypress v9

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      APPLITOOLS_API_KEY:
        required: true

permissions:
  contents: read

jobs:
  batch_id:
    name: Batch_id
    runs-on: ubuntu-latest
    outputs:
      uuid: ${{ steps.uuid.outputs.uuid }}
    steps:
      - name: generate uuid
        id: uuid
        run: |
          echo "::set-output name=uuid::$(uuidgen)"
  test:
    needs: batch_id
    strategy:
      matrix:
        node-version: [ '16' ]
        exact: ['9.7.0', '9.6.1', '8.7.0', '7.7.0', '6.9.1']
    runs-on: ubuntu-latest
    env:
      APPLITOOLS_DONT_CLOSE_BATCHES: true
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
      APPLITOOLS_BATCH_ID: ${{needs.batch_id.outputs.uuid}}
    name: ${{runner.os}} | ${{matrix.exact}}
    defaults:
      run:
        working-directory: 'sdks/js/eyes-cypress/v9'
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Default install
        run: npm install
      - name: Framework install
        uses: ./.github/actions/install_npm_package
        with:
          package: cypress
          exact: ${{matrix.exact}}
          working-directory: 'sdks/js/eyes-cypress/v9'
      - name: Log installed packages
        run: npm ls
      - name: Run tests
        run: npm test