name: JS Nightwatch

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      APPLITOOLS_API_KEY:
        required: true

permissions:
  contents: read

env:
  work_dir: 'sdks/js/eyes-nightwatch'


jobs:
  batch_id:
    name: Batch_id
    runs-on: ubuntu-latest
    outputs:
      uuid: ${{ steps.uuid.outputs.uuid }}
    steps:
      - name: generate uuid
        id: uuid
        run: |
          echo "::set-output name=uuid::$(uuidgen)"
  test:
    needs: batch_id
    strategy:
      fail-fast: false
      matrix:
        node-version: [ '16' ]
        os: [windows-latest, ubuntu-latest, macos-latest]
        major: [ 0 ]
        include:
          - node-version: '16'
            os: ubuntu-latest
            major: -1
    runs-on: ${{ matrix.os }}
    env:
      APPLITOOLS_DONT_CLOSE_BATCHES: true
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
      APPLITOOLS_BATCH_ID: ${{needs.batch_id.outputs.uuid}}
    name: ${{ matrix.os }} | major ${{matrix.major}}
    defaults:
      run:
        working-directory: ${{env.work_dir}}
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run Selenium
        if: matrix.major == 0
        uses: ./.github/actions/start_selenium
      - name: Run Selenium
        if: matrix.major != 0
        uses: ./.github/actions/start_selenium
        with:
          legacy: 'true'
      - name: Framework install
        uses: ./.github/actions/install_npm_package
        with:
          package: nightwatch
          major: ${{matrix.major}}
          working-directory: ${{env.work_dir}}
      - name: Run Install
        run: npm install
      - name: Log installed packages
        run: npm ls
      - name: Run tests
        run: |
          npm test
          USE_UFG=true npm test