name: JS Protractor

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      APPLITOOLS_API_KEY:
        required: true

permissions:
  contents: read

env:
  work_dir: 'sdks/js/eyes-protractor'

jobs:
  batch_id:
    name: Batch_id
    runs-on: ubuntu-latest
    outputs:
      uuid: ${{ steps.uuid.outputs.uuid }}
    steps:
      - name: generate uuid
        id: uuid
        run: |
          echo "uuid=$(uuidgen)" >> $GITHUB_OUTPUT
  test:
    needs: batch_id
    strategy:
      fail-fast: false
      matrix:
        node-version: [ '16' ]
        os: [windows-latest, ubuntu-latest, macos-latest]
        major: [ 0 ]
        include:
          - node-version: '16'
            os: ubuntu-latest
            major: -2
    runs-on: ${{ matrix.os }}
    env:
      APPLITOOLS_DONT_CLOSE_BATCHES: true
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
      APPLITOOLS_BATCH_ID: ${{needs.batch_id.outputs.uuid}}
      JS_TESTS_CONFIG_NAME: 'eyes-protractor'
    name: ${{matrix.os}} | major ${{matrix.major}}
    defaults:
      run:
        working-directory: ${{env.work_dir}}
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Start Selenium Server
        uses: ./.github/actions/start_selenium
      - name: Framework install
        id: install
        uses: ./.github/actions/install_npm_package
        with:
          package: protractor
          major: ${{matrix.major}}
          working-directory: ${{env.work_dir}}
      - name: Run Install
        run: npm install
      - name: Log installed packages
        run: npm ls
      - name: Logging version generation
        uses: ./.github/actions/log_data_json
        with:
          package: 'Protractor'
          version: ${{ steps.install.outputs.package_version }}
          os: ${{runner.os}}
          title: ${{ format('Protractor version {1} [{0}] [{2}]', runner.os, steps.install.outputs.package_version, matrix.node-version) }}
          selenium: '4'
      - name: Run tests
        run: npm test