name: JS Protractor

on:
  workflow_dispatch:
    inputs:
      last_passed:
        description: ' Check to make last passed run'
        default: false
        required: true
        type: boolean
  workflow_call:
    inputs:
      last_passed:
        description: 'choose which version of the frameworks should be used (latest | last passed)'
        default: false
        required: true
        type: boolean
    secrets:
      APPLITOOLS_API_KEY:
        required: true

permissions:
  contents: read

env:
  work_dir: 'sdks/js/eyes-protractor'

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      uuid: ${{ steps.uuid.outputs.uuid }}
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: generate uuid
        id: uuid
        run: |
          echo "uuid=$(uuidgen)" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v3
      - name: generate matrix
        id: matrix
        uses: ./.github/actions/setup
        with:
          work_dir: ${{env.work_dir}}
          last_passed: ${{inputs.last_passed}}
  test:
    needs: setup
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    env:
      APPLITOOLS_DONT_CLOSE_BATCHES: true
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
      APPLITOOLS_BATCH_ID: ${{needs.setup.outputs.uuid}}
      JS_TESTS_CONFIG_NAME: ${{matrix.js_config}}
    name: ${{matrix.os}} | ${{matrix.version}}
    defaults:
      run:
        working-directory: ${{matrix.work_dir}}
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Start Selenium Server
        id: selenium
        uses: ./.github/actions/start_selenium
      - name: Framework install
        id: install
        uses: ./.github/actions/install_npm_package
        with:
          package: protractor
          version: ${{matrix.version}}
          working-directory: ${{matrix.work_dir}}
      - name: Run Install
        run: npm install
      - name: Log installed packages
        run: npm ls
      - name: Log extra info
        id: logging
        run: |
          chromedriver --version
          echo "chromedriver_version=$(chromedriver --version)" >> $GITHUB_OUTPUT
          if [ "$RUNNER_OS" == "Linux" ]; then
               google-chrome --version
               echo "chrome_version=$(google-chrome --version)" >> $GITHUB_OUTPUT
          elif [ "$RUNNER_OS" == "Windows" ]; then
               powershell.exe -command "(Get-Item 'C:\Program Files\Google\Chrome\Application\chrome.exe').VersionInfo.ProductVersion"
               echo "chrome_version=$(powershell.exe -command "(Get-Item 'C:\Program Files\Google\Chrome\Application\chrome.exe').VersionInfo.ProductVersion")" >> $GITHUB_OUTPUT
          elif [ "$RUNNER_OS" == "macOS" ]; then
               /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version 
               echo "chrome_version=$(/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version)" >> $GITHUB_OUTPUT
          else
               echo "$RUNNER_OS not supported"
               exit 1
          fi
      - name: Logging version generation
        uses: ./.github/actions/log_data_json
        with:
          package: 'Protractor'
          version: ${{ steps.install.outputs.package_version }}
          os: ${{runner.os}}
          matrix_os: ${{matrix.os}}
          work_dir: ${{matrix.work_dir}}
          title: ${{ format('Protractor version {1} [{0}] [nodejs {2}]', runner.os, steps.install.outputs.package_version, matrix.node-version) }}
          selenium:  ${{ steps.selenium.outputs.version }}
          chrome_version: ${{ steps.logging.outputs.chrome_version }}
          chromedriver_version: ${{ steps.logging.outputs.chromedriver_version }}
      - name: Run tests
        run: npm test