name: JS Playwright

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      APPLITOOLS_API_KEY:
        required: true

permissions:
  contents: read

env:
  APPLITOOLS_DONT_CLOSE_BATCHES: true
  APPLITOOLS_BATCH_ID: ${{  github.sha }}

jobs:
  selenium:
    strategy:
      fail-fast: false
      matrix:
        include:
          - node-version: '16'
            os: windows-latest
          - node-version: '16'
            os: ubuntu-latest
          - node-version: '16'
            os: macos-latest
    runs-on: ${{ matrix.os }}
    env:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
    name: JS Selenium nodejs = ${{ matrix.node-version }} | os = ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run tests
        working-directory: sdks/js/eyes-playwright
        run: |
          npm install
          npx playwright install --with-deps
          npm test