name: JS Playwright

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      APPLITOOLS_API_KEY:
        required: true

permissions:
  contents: read

jobs:
  batch_id:
    name: Batch_id
    runs-on: ubuntu-latest
    outputs:
      uuid: ${{ steps.uuid.outputs.uuid }}
    steps:
      - name: generate uuid
        id: uuid
        run: |
          echo "::set-output name=uuid::$(uuidgen)"
  test:
    needs: batch_id
    strategy:
      fail-fast: false
      matrix:
        include:
          - node-version: '16'
            os: windows-latest
          - node-version: '16'
            os: ubuntu-latest
          - node-version: '16'
            os: macos-latest
    runs-on: ${{ matrix.os }}
    env:
      APPLITOOLS_DONT_CLOSE_BATCHES: true
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
      APPLITOOLS_BATCH_ID: ${{needs.batch_id.outputs.uuid}}
    name: ${{ matrix.node-version }} | ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run tests
        working-directory: sdks/js/eyes-playwright
        run: |
          npm install
          npx playwright install --with-deps
          npm test