name: JS framework group

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  js_selenium:
    uses: ./.github/workflows/js_selenium.yml
    with:
      last_passed: false
    secrets:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
  js_cypress:
    uses: ./.github/workflows/js_cypress.yml
    with:
      last_passed: false
    secrets:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}