name: JS framework group

on:
  workflow_dispatch:
    inputs:
      last_passed:
        description: ' Check to make last passed run'
        default: false
        required: true
        type: boolean
      eyes_version:
        description: 'Set the version which should be used for the eyes SDK'
        default: 'latest@'
        required: false
  workflow_call:
    secrets:
      APPLITOOLS_API_KEY:
        required: true

permissions:
  contents: read

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      uuid: ${{ steps.uuid.outputs.uuid }}
      web: ${{ steps.matrix.outputs.web}}
      appium: ${{ steps.matrix.outputs.appium}}
    steps:
      - name: generate uuid
        id: uuid
        run: |
          echo "uuid=$(uuidgen)" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v3
      - name: generate matrix
        id: matrix
        uses: ./.github/actions/setup
        with:
          work_dir: 'sdks/js/eyes-webdriverio, sdks/js/eyes-testcafe, sdks/js/eyes-storybook, sdks/js/eyes-puppeteer, sdks/js/eyes-protractor, sdks/js/eyes-playwright, sdks/js/eyes-nightwatch, sdks/js/eyes-cypress, sdks/js/eyes-selenium, sdks/python, sdks/java, sdks/dotnet, sdks/ruby'
          last_passed: ${{inputs.last_passed}}
  test:
    needs: setup
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup.outputs.web) }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    env:
      APPLITOOLS_DONT_CLOSE_BATCHES: true
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
      APPLITOOLS_BATCH_ID: ${{needs.setup.outputs.uuid}}
      APPLITOOLS_BRANCH_NAME: ${{matrix.branch}}
      JS_TESTS_CONFIG_NAME: ${{matrix.js_config}}
    name: ${{ matrix.job_name }}
    defaults:
      run:
        working-directory: ${{matrix.work_dir}}
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Test
        uses: ./.github/actions/test_runner
        with:
          lang: ${{matrix.test_runner}}
          eyes_version: ${{inputs.eyes_version}}
#  appium:
#    needs: setup
#    strategy:
#      max-parallel: 8
#      fail-fast: false
#      matrix: ${{ fromJson(needs.setup.outputs.appium) }}
#    runs-on: ${{ matrix.os }}
#    timeout-minutes: 15
#    env:
#      APPLITOOLS_DONT_CLOSE_BATCHES: true
#      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
#      APPLITOOLS_BATCH_ID: ${{needs.setup.outputs.uuid}}
#      APPLITOOLS_BRANCH_NAME: ${{matrix.branch}}
#      JS_TESTS_CONFIG_NAME: ${{matrix.js_config}}
#      SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
#      SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
#    name: ${{ matrix.job_name }}
#    defaults:
#      run:
#        working-directory: ${{matrix.work_dir}}
#        shell: bash
#    steps:
#      - uses: actions/checkout@v3
#      - name: Test
#        uses: ./.github/actions/test_runner
#        with:
#          lang: ${{matrix.test_runner}}
#          eyes_version: ${{inputs.eyes_version}}