name: JS selenium

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      APPLITOOLS_API_KEY:
        required: true

permissions:
  contents: read

jobs:
  batch_id:
    name: Batch_id
    runs-on: ubuntu-latest
    outputs:
      uuid: ${{ steps.uuid.outputs.uuid }}
    steps:
      - name: generate uuid
        id: uuid
        run: |
          echo "::set-output name=uuid::$(uuidgen)"
  test:
    needs: batch_id
    strategy:
      fail-fast: false
      matrix:
        node-version: [ '16' ]
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      APPLITOOLS_DONT_CLOSE_BATCHES: true
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
      APPLITOOLS_BATCH_ID: ${{needs.batch_id.outputs.uuid}}
      JS_TESTS_CONFIG_NAME: 'eyes-selenium'
    name: ${{ matrix.node-version }} | ${{matrix.os}}
    defaults:
      run:
        working-directory: 'sdks/js/eyes-selenium'
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Start Selenium Server
        uses: ./.github/actions/start_selenium
      - name: Logging version generation
        uses: ./.github/actions/log_data_json
        with:
          os: ${{runner.os}}
          title: ${{ format('{0} | Pure selenium', runner.os) }}
          selenium: '4'
      - name: Run tests
        run: |
          npm install
          npm test