name: JS Testcafe

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      APPLITOOLS_API_KEY:
        required: true

permissions:
  contents: read

env:
  work_dir: 'sdks/js/eyes-testcafe'


jobs:
  batch_id:
    name: Batch_id
    runs-on: ubuntu-latest
    outputs:
      uuid: ${{ steps.uuid.outputs.uuid }}
    steps:
      - name: generate uuid
        id: uuid
        run: |
          echo "uuid=$(uuidgen)" >> $GITHUB_OUTPUT
  test:
    needs: batch_id
    strategy:
      fail-fast: false
      matrix:
        node-version: [ '16' ]
        os: [windows-latest, ubuntu-latest]
        major: [0]
        include:
          - node-version: '16'
            os: ubuntu-latest
            major: -1
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    env:
      APPLITOOLS_DONT_CLOSE_BATCHES: true
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
      APPLITOOLS_BATCH_ID: ${{needs.batch_id.outputs.uuid}}
    name: ${{matrix.os}} | minor ${{matrix.minor}}
    defaults:
      run:
        working-directory:  ${{env.work_dir}}
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Default install
        run: npm install
      - name: Framework install
        id: install
        uses: ./.github/actions/install_npm_package
        with:
          package: testcafe
          major: ${{matrix.major}}
          working-directory:  ${{env.work_dir}}
      - name: Log installed packages
        run: npm ls
      - name: Log extra info
        id: logging
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
               google-chrome --version
               echo "chrome_version=$(google-chrome --version)" >> $GITHUB_OUTPUT
          elif [ "$RUNNER_OS" == "Windows" ]; then
               echo "Getting chrome version isn't supported for windows (((("
               echo "chrome_version=$(powershell.exe -command "(Get-Item 'C:\Program Files\Google\Chrome\Application\chrome.exe').VersionInfo.ProductVersion")" >> $GITHUB_OUTPUT
          elif [ "$RUNNER_OS" == "macOS" ]; then
               /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version 
               echo "chrome_version=$(/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version)" >> $GITHUB_OUTPUT
          else
               echo "$RUNNER_OS not supported"
               exit 1
          fi
      - name: Logging version generation
        uses: ./.github/actions/log_data_json
        with:
          package: 'Testcafe'
          version: ${{ steps.install.outputs.package_version }}
          os: ${{runner.os}}
          title: ${{ format('Testcafe version {1} [{0}] [nodejs {2}]', runner.os, steps.install.outputs.package_version, matrix.node-version) }}
          selenium: 'None'
          chrome_version: ${{ steps.logging.outputs.chrome_version }}
      - name: Run tests
        run: npm test
