name: JS WebdriverIO5

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      APPLITOOLS_API_KEY:
        required: true

permissions:
  contents: read

jobs:
  batch_id:
    name: Batch_id
    runs-on: ubuntu-latest
    outputs:
      uuid: ${{ steps.uuid.outputs.uuid }}
    steps:
      - name: generate uuid
        id: uuid
        run: |
          echo "uuid=$(uuidgen)" >> $GITHUB_OUTPUT
  tests:
    needs: batch_id
    strategy:
      fail-fast: false
      matrix:
        include:
          - node-version: '16'
            os: windows-latest
          - node-version: '16'
            os: ubuntu-latest
          - node-version: '16'
            os: macos-latest
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.node-version }} | ${{matrix.os}} | 5
    env:
      APPLITOOLS_DONT_CLOSE_BATCHES: true
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
      APPLITOOLS_BATCH_ID: ${{needs.batch_id.outputs.uuid}}
      JS_TESTS_CONFIG_NAME: 'eyes-webdriverio/5'
    defaults:
      run:
        working-directory: 'sdks/js/eyes-webdriverio/5'
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run Selenium
        uses: ./.github/actions/start_selenium
        with:
          legacy: 'true'
      - name: Logging version generation
        uses: ./.github/actions/log_data_json
        with:
          package: 'Webdriverio'
          version: '5.23.0'
          os: ${{runner.os}}
          title: ${{ format('Webdriverio version 5.23.0 [{0}], [{1}]', runner.os, matrix.node-version) }}
          selenium: '3'
      - name: Run tests
        run: |
          npm install
          npm test    
