name: JS WebdriverIO

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      APPLITOOLS_API_KEY:
        required: true

permissions:
  contents: read

env:
  APPLITOOLS_BATCH_ID: ${{  github.sha }}
  APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}

jobs:
  tests:
    strategy:
      matrix:
        node-version: [ '16' ]
        os: [windows-latest, ubuntu-latest, macos-latest]
        webdriverio-version: ['5','6','7']
    runs-on: ${{ matrix.os }}
    name: JS Selenium nodejs = ${{ matrix.node-version }} | os = ${{matrix.os}} | webdriverio version = ${{matrix.webdriverio-version}}
    env:
      APPLITOOLS_DONT_CLOSE_BATCHES: true
    defaults:
      run:
        working-directory: ${{format(sdks/js/eyes-webdriverio/${0}, matrix.webdriverio-version)}}
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run Selenium
        uses: ./.github/actions/start_selenium
      - name: Run tests
        run: |
          npm install
          npm test