name: Python

on:
  workflow_dispatch:
    inputs:
      last_passed:
        description: ' Check to make last passed run'
        default: false
        required: true
        type: boolean
      eyes_version:
        description: 'Set the version which should be used for the eyes SDK'
        default: 'latest@'
        required: false
  workflow_call:
    inputs:
      last_passed:
        description: 'choose which version of the frameworks should be used (latest | last passed)'
        default: false
        required: true
        type: boolean
      eyes_version:
        description: 'Set the version which should be used for the eyes SDK'
        default: 'latest@'
        type: string
        required: false
      checkout_ref:
        description: 'set ref when used from the another repo'
        default: ''
        required: false
        type: string
    secrets:
      APPLITOOLS_API_KEY:
        required: true
      SAUCE_USERNAME:
        required: true
      SAUCE_ACCESS_KEY:
        required: true

permissions:
  contents: read

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      uuid: ${{ steps.uuid.outputs.uuid }}
      matrix: ${{ steps.matrix.outputs.matrix}}
    steps:
      - name: generate uuid
        id: uuid
        run: |
          echo "uuid=$(uuidgen)" >> $GITHUB_OUTPUT
          env
      - uses: actions/checkout@v3
        with:
          repository: applitools/applitools_support_matrix
          ref: ${{inputs.checkout_ref}}
      - name: generate matrix
        id: matrix
        uses: ./.github/actions/setup
        with:
          work_dir: 'sdks/python'
          last_passed: ${{inputs.last_passed}}
  test:
    needs: setup
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    env:
      APPLITOOLS_DONT_CLOSE_BATCHES: true
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
      APPLITOOLS_BATCH_ID: ${{needs.setup.outputs.uuid}}
      SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
      SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
    defaults:
      run:
        working-directory: ${{matrix.work_dir}}
        shell: bash
    name:  ${{ matrix.job_name }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: applitools/applitools_support_matrix
          ref: ${{inputs.checkout_ref}}
      - name: Test
        uses: ./.github/actions/test_runner
        with:
          lang: ${{matrix.test_runner}}
          eyes_version: ${{inputs.eyes_version}}