name: Python

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      APPLITOOLS_API_KEY:
        required: true

permissions:
  contents: read

env:
  APPLITOOLS_DONT_CLOSE_BATCHES: true

jobs:
  test:
    strategy:
      matrix:
        python-version: [ '3.10' ]
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
    name: Python ${{ matrix.python-version }} ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tests
        working-directory: sdks/python
        run: |
          pip install -r requirements.txt
          pytest -n 2