name: Python

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  
jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ '3.10' ]
    env:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tests
        working-directory: sdks/python
        run: |
          pip install -r requirements.txt
          pytest -n 2