name: Rerun failed
on:
  workflow_dispatch:
    inputs:
      run_id:
        required: true
        description: rerun id


jobs:
  rerun:
    runs-on: ubuntu-latest
    steps:
      - name: Small wait before initiated workflow have finished
        run: sleep 100
      - name: rerun
        run: curl -X POST -s -u "admin:${{ secrets.PAT }}" https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ inputs.run_id }}/rerun-failed-jobs
