name: Ruby

on:
  workflow_dispatch:
  push:

permissions:
  contents: read
  
jobs:
  test:
    needs: dist-build
    runs-on: windows-latest
    strategy:
      matrix:
        ruby-version: [ '2.6' ]
    env:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run tests
        working-directory: sdks/ruby
        run: |
          bundle install
          bundle exec rake