name: Ruby

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      APPLITOOLS_API_KEY:
        required: true

permissions:
  contents: read

jobs:
  batch_id:
    uses: ./.github/workflows/batch_id.yml
  test:
    needs: batch_id
    strategy:
      matrix:
        ruby-version: [ '2.6' ]
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      APPLITOOLS_DONT_CLOSE_BATCHES: true
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
      APPLITOOLS_BATCH_ID: ${{needs.batch_id.outputs.uuid}}
    name: ${{ matrix.ruby-version }} | ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Install gems
        working-directory: sdks/ruby
        run: |
          bundle install
      - name: Start Selenium Server
        uses: ./.github/actions/start_selenium
      - name: Run tests
        working-directory: sdks/ruby
        run: |
          bundle exec rake