name: Ruby

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      APPLITOOLS_API_KEY:
        required: true

permissions:
  contents: read
  
jobs:
  test:
    strategy:
      matrix:
        ruby-version: [ '2.6' ]
    runs-on: windows-latest
    env:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
    name: Ruby ${{ ruby-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Install gems
        working-directory: sdks/ruby
        run: |
          bundle install
      - name: Run tests
        working-directory: sdks/ruby
        run: |
          bundle exec rake