name: Test Appium tests

on:
  workflow_dispatch:
    inputs:
      orientation:
        description: "Select device orientation which will be used during the run"
        required: true
        default: 'PORTRAIT'
        type: choice
        options:
          - 'PORTRAIT'
          - 'LANDSCAPE'

permissions:
  contents: write

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      uuid: ${{ steps.uuid.outputs.uuid }}
      web: ${{ steps.matrix.outputs.web}}
      appium: ${{ steps.matrix.outputs.appium}}
    steps:
      - name: generate uuid
        id: uuid
        run: |
          echo "uuid=$(uuidgen)" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v3
      - name: generate matrix
        id: matrix
        uses: ./.github/actions/setup
        with:
#          work_dir: 'sdks/js/eyes-webdriverio, sdks/js/eyes-testcafe, sdks/js/eyes-storybook, sdks/js/eyes-puppeteer, sdks/js/eyes-protractor, sdks/js/eyes-playwright, sdks/js/eyes-nightwatch, sdks/js/eyes-cypress, sdks/js/eyes-selenium, sdks/python, sdks/java, sdks/dotnet, sdks/ruby'
#          work_dir: 'sdks/js/eyes-selenium'
          work_dir: 'sdks/js/eyes-selenium, sdks/js/eyes-webdriverio, sdks/python/appium, sdks/java/appium, sdks/dotnet/appium, sdks/ruby/appium'
          last_passed: false
  appium:
    needs: setup
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix: ${{ fromJson(needs.setup.outputs.appium) }}
    runs-on: ${{ matrix.os }}
    environment: ${{matrix.gh_environment}}
    timeout-minutes: 20
    env:
      APPLITOOLS_DONT_CLOSE_BATCHES: true
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
      APPLITOOLS_BATCH_ID: ${{needs.setup.outputs.uuid}}
      JS_TESTS_CONFIG_NAME: ${{matrix.js_config}}
      SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
      SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
      APPIUM_VERSION: ${{vars.APPIUM_VERSION}}
      MATRIX_DEVICE_ORIENTATION: ${{inputs.orientation}}
    name: ${{ matrix.job_name }}
    defaults:
      run:
        working-directory: ${{matrix.work_dir}}
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Test
        uses: ./.github/actions/test_runner
        with:
          lang: ${{matrix.test_runner}}